# Generated by Django 4.2.4 on 2023-10-06 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=20)),
                ("branch", models.CharField(max_length=30)),
                ("userTag", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=50)),
                ("hashtags", models.TextField()),
                ("created", models.DateTimeField()),
                ("lastModified", models.DateTimeField()),
                ("deadline", models.DateTimeField(null=True)),
                (
                    "createdBy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_owner",
                        to="doc.user",
                    ),
                ),
                (
                    "lastEditBy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doc_lastEditBy",
                        to="doc.user",
                    ),
                ),
            ],
        ),
    ]
