# Generated by Django 4.2.4 on 2023-10-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doc", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("tag", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="document",
            name="content",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="user",
            name="enrollmentNo",
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="profile",
            field=models.ImageField(null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="document",
            name="hashtags",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AddField(
            model_name="user",
            name="group",
            field=models.ManyToManyField(to="doc.group"),
        ),
    ]
