# Generated by Django 4.2.6 on 2023-10-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doc", "0005_alter_user_email_alter_user_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="year",
            field=models.IntegerField(null=True),
        ),
    ]
