# Generated by Django 4.2.6 on 2023-10-27 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("doc", "0009_alter_user_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="access_token",
        ),
        migrations.RemoveField(
            model_name="user",
            name="refresh_token",
        ),
        migrations.AlterField(
            model_name="document",
            name="createdBy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="lastEditBy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lastEditBy",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="template",
        ),
    ]
