# Generated by Django 4.2.6 on 2023-10-29 10:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doc", "0010_remove_user_access_token_remove_user_refresh_token_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="hashtags",
        ),
        migrations.AlterField(
            model_name="document",
            name="content",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
